# Generated by Django 3.1.13 on 2021-11-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adultcontent', models.BooleanField(default=False)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
